// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_GAMEFILE_GAMEFILE_H_
#define FLATBUFFERS_GENERATED_GAMEFILE_GAMEFILE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace gamefile {

struct Vec3;

struct Entity;
struct EntityBuilder;

struct TextFile;
struct TextFileBuilder;

struct GameFile;
struct GameFileBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vec3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vec3(float _x, float _y, float _z)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 12);

struct Entity FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EntityBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POSITION = 4
  };
  const gamefile::Vec3 *position() const {
    return GetStruct<const gamefile::Vec3 *>(VT_POSITION);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<gamefile::Vec3>(verifier, VT_POSITION, 4) &&
           verifier.EndTable();
  }
};

struct EntityBuilder {
  typedef Entity Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_position(const gamefile::Vec3 *position) {
    fbb_.AddStruct(Entity::VT_POSITION, position);
  }
  explicit EntityBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Entity> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Entity>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Entity> CreateEntity(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const gamefile::Vec3 *position = nullptr) {
  EntityBuilder builder_(_fbb);
  builder_.add_position(position);
  return builder_.Finish();
}

struct TextFile FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TextFileBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SHADER = 4
  };
  const ::flatbuffers::String *shader() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SHADER);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SHADER) &&
           verifier.VerifyString(shader()) &&
           verifier.EndTable();
  }
};

struct TextFileBuilder {
  typedef TextFile Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_shader(::flatbuffers::Offset<::flatbuffers::String> shader) {
    fbb_.AddOffset(TextFile::VT_SHADER, shader);
  }
  explicit TextFileBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TextFile> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TextFile>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TextFile> CreateTextFile(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> shader = 0) {
  TextFileBuilder builder_(_fbb);
  builder_.add_shader(shader);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TextFile> CreateTextFileDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *shader = nullptr) {
  auto shader__ = shader ? _fbb.CreateString(shader) : 0;
  return gamefile::CreateTextFile(
      _fbb,
      shader__);
}

struct GameFile FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GameFileBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERSION = 4,
    VT_VERTEX_SHADER = 6,
    VT_FRAGMENT_SHADER = 8,
    VT_ENTITIES = 10
  };
  int32_t version() const {
    return GetField<int32_t>(VT_VERSION, 0);
  }
  const gamefile::TextFile *vertex_shader() const {
    return GetPointer<const gamefile::TextFile *>(VT_VERTEX_SHADER);
  }
  const gamefile::TextFile *fragment_shader() const {
    return GetPointer<const gamefile::TextFile *>(VT_FRAGMENT_SHADER);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<gamefile::Entity>> *entities() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<gamefile::Entity>> *>(VT_ENTITIES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_VERSION, 4) &&
           VerifyOffset(verifier, VT_VERTEX_SHADER) &&
           verifier.VerifyTable(vertex_shader()) &&
           VerifyOffset(verifier, VT_FRAGMENT_SHADER) &&
           verifier.VerifyTable(fragment_shader()) &&
           VerifyOffset(verifier, VT_ENTITIES) &&
           verifier.VerifyVector(entities()) &&
           verifier.VerifyVectorOfTables(entities()) &&
           verifier.EndTable();
  }
};

struct GameFileBuilder {
  typedef GameFile Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_version(int32_t version) {
    fbb_.AddElement<int32_t>(GameFile::VT_VERSION, version, 0);
  }
  void add_vertex_shader(::flatbuffers::Offset<gamefile::TextFile> vertex_shader) {
    fbb_.AddOffset(GameFile::VT_VERTEX_SHADER, vertex_shader);
  }
  void add_fragment_shader(::flatbuffers::Offset<gamefile::TextFile> fragment_shader) {
    fbb_.AddOffset(GameFile::VT_FRAGMENT_SHADER, fragment_shader);
  }
  void add_entities(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<gamefile::Entity>>> entities) {
    fbb_.AddOffset(GameFile::VT_ENTITIES, entities);
  }
  explicit GameFileBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GameFile> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GameFile>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<GameFile> CreateGameFile(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t version = 0,
    ::flatbuffers::Offset<gamefile::TextFile> vertex_shader = 0,
    ::flatbuffers::Offset<gamefile::TextFile> fragment_shader = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<gamefile::Entity>>> entities = 0) {
  GameFileBuilder builder_(_fbb);
  builder_.add_entities(entities);
  builder_.add_fragment_shader(fragment_shader);
  builder_.add_vertex_shader(vertex_shader);
  builder_.add_version(version);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<GameFile> CreateGameFileDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t version = 0,
    ::flatbuffers::Offset<gamefile::TextFile> vertex_shader = 0,
    ::flatbuffers::Offset<gamefile::TextFile> fragment_shader = 0,
    const std::vector<::flatbuffers::Offset<gamefile::Entity>> *entities = nullptr) {
  auto entities__ = entities ? _fbb.CreateVector<::flatbuffers::Offset<gamefile::Entity>>(*entities) : 0;
  return gamefile::CreateGameFile(
      _fbb,
      version,
      vertex_shader,
      fragment_shader,
      entities__);
}

inline const gamefile::GameFile *GetGameFile(const void *buf) {
  return ::flatbuffers::GetRoot<gamefile::GameFile>(buf);
}

inline const gamefile::GameFile *GetSizePrefixedGameFile(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<gamefile::GameFile>(buf);
}

inline bool VerifyGameFileBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<gamefile::GameFile>(nullptr);
}

inline bool VerifySizePrefixedGameFileBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<gamefile::GameFile>(nullptr);
}

inline void FinishGameFileBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<gamefile::GameFile> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedGameFileBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<gamefile::GameFile> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace gamefile

#endif  // FLATBUFFERS_GENERATED_GAMEFILE_GAMEFILE_H_
